version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Use Node.js 16 for better Angular compatibility
    commands:
      - npm install -g @angular/cli@17

  pre_build:
    commands:
      - npm ci  # Clean install to avoid dependency conflicts

  build:
    commands:
      - ng build -c production

  post_build:
    commands:
      - echo 'Build completed successfully!'

artifacts:
  files:
    - 'dist/edltestartifact/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'