version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build -c production

  post_build:
    commands:
      - echo 'Build completed successfully!'

artifacts:
  files:
    - 'dist/edltestartifact/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'