version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v

  build:
    commands:
      - npm install --legacy-peer-deps
      - npm run build

artifacts:
  files:
    - 'build/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'